// Form demos: a start and end photo per exercise from free-exercise-db
// (github.com/yuhonas/free-exercise-db, public domain), resized to 400 px wide and bundled
// so they work offline on the gym floor. ExerciseDemo crossfades the two frames.
//
// Lookup is by normalized exercise name, so program prefixes ("Superset A1: ") and
// parentheticals ("(heavy wk: …)", "(bottom half)") fall away. Some demos are the nearest
// equivalent (a barbell hip thrust for the Smith version); the cue under the name has the specifics.
import type { ImageSourcePropType } from 'react-native';

type Frames = [ImageSourcePropType, ImageSourcePropType];

const FRAMES = {
  'ab-crunch-machine': [require('@/assets/demos/ab-crunch-machine-0.jpg'), require('@/assets/demos/ab-crunch-machine-1.jpg')],
  'ab-roller': [require('@/assets/demos/ab-roller-0.jpg'), require('@/assets/demos/ab-roller-1.jpg')],
  'arnold-dumbbell-press': [require('@/assets/demos/arnold-dumbbell-press-0.jpg'), require('@/assets/demos/arnold-dumbbell-press-1.jpg')],
  'barbell-bench-press-medium-grip': [require('@/assets/demos/barbell-bench-press-medium-grip-0.jpg'), require('@/assets/demos/barbell-bench-press-medium-grip-1.jpg')],
  'barbell-curl': [require('@/assets/demos/barbell-curl-0.jpg'), require('@/assets/demos/barbell-curl-1.jpg')],
  'barbell-deadlift': [require('@/assets/demos/barbell-deadlift-0.jpg'), require('@/assets/demos/barbell-deadlift-1.jpg')],
  'barbell-hip-thrust': [require('@/assets/demos/barbell-hip-thrust-0.jpg'), require('@/assets/demos/barbell-hip-thrust-1.jpg')],
  'barbell-incline-bench-press-medium-grip': [require('@/assets/demos/barbell-incline-bench-press-medium-grip-0.jpg'), require('@/assets/demos/barbell-incline-bench-press-medium-grip-1.jpg')],
  'barbell-shrug': [require('@/assets/demos/barbell-shrug-0.jpg'), require('@/assets/demos/barbell-shrug-1.jpg')],
  'barbell-squat': [require('@/assets/demos/barbell-squat-0.jpg'), require('@/assets/demos/barbell-squat-1.jpg')],
  'bent-over-barbell-row': [require('@/assets/demos/bent-over-barbell-row-0.jpg'), require('@/assets/demos/bent-over-barbell-row-1.jpg')],
  'butt-lift-bridge': [require('@/assets/demos/butt-lift-bridge-0.jpg'), require('@/assets/demos/butt-lift-bridge-1.jpg')],
  'cable-crossover': [require('@/assets/demos/cable-crossover-0.jpg'), require('@/assets/demos/cable-crossover-1.jpg')],
  'cable-crunch': [require('@/assets/demos/cable-crunch-0.jpg'), require('@/assets/demos/cable-crunch-1.jpg')],
  'cable-rope-overhead-triceps-extension': [require('@/assets/demos/cable-rope-overhead-triceps-extension-0.jpg'), require('@/assets/demos/cable-rope-overhead-triceps-extension-1.jpg')],
  'cable-shrugs': [require('@/assets/demos/cable-shrugs-0.jpg'), require('@/assets/demos/cable-shrugs-1.jpg')],
  'calf-press-on-the-leg-press-machine': [require('@/assets/demos/calf-press-on-the-leg-press-machine-0.jpg'), require('@/assets/demos/calf-press-on-the-leg-press-machine-1.jpg')],
  'concentration-curls': [require('@/assets/demos/concentration-curls-0.jpg'), require('@/assets/demos/concentration-curls-1.jpg')],
  'crunches': [require('@/assets/demos/crunches-0.jpg'), require('@/assets/demos/crunches-1.jpg')],
  'dips-chest-version': [require('@/assets/demos/dips-chest-version-0.jpg'), require('@/assets/demos/dips-chest-version-1.jpg')],
  'dips-triceps-version': [require('@/assets/demos/dips-triceps-version-0.jpg'), require('@/assets/demos/dips-triceps-version-1.jpg')],
  'dumbbell-bicep-curl': [require('@/assets/demos/dumbbell-bicep-curl-0.jpg'), require('@/assets/demos/dumbbell-bicep-curl-1.jpg')],
  'dumbbell-flyes': [require('@/assets/demos/dumbbell-flyes-0.jpg'), require('@/assets/demos/dumbbell-flyes-1.jpg')],
  'dumbbell-lunges': [require('@/assets/demos/dumbbell-lunges-0.jpg'), require('@/assets/demos/dumbbell-lunges-1.jpg')],
  'dumbbell-shoulder-press': [require('@/assets/demos/dumbbell-shoulder-press-0.jpg'), require('@/assets/demos/dumbbell-shoulder-press-1.jpg')],
  'ez-bar-curl': [require('@/assets/demos/ez-bar-curl-0.jpg'), require('@/assets/demos/ez-bar-curl-1.jpg')],
  'ez-bar-skullcrusher': [require('@/assets/demos/ez-bar-skullcrusher-0.jpg'), require('@/assets/demos/ez-bar-skullcrusher-1.jpg')],
  'face-pull': [require('@/assets/demos/face-pull-0.jpg'), require('@/assets/demos/face-pull-1.jpg')],
  'front-barbell-squat': [require('@/assets/demos/front-barbell-squat-0.jpg'), require('@/assets/demos/front-barbell-squat-1.jpg')],
  'front-plate-raise': [require('@/assets/demos/front-plate-raise-0.jpg'), require('@/assets/demos/front-plate-raise-1.jpg')],
  'hammer-curls': [require('@/assets/demos/hammer-curls-0.jpg'), require('@/assets/demos/hammer-curls-1.jpg')],
  'hanging-leg-raise': [require('@/assets/demos/hanging-leg-raise-0.jpg'), require('@/assets/demos/hanging-leg-raise-1.jpg')],
  'incline-dumbbell-curl': [require('@/assets/demos/incline-dumbbell-curl-0.jpg'), require('@/assets/demos/incline-dumbbell-curl-1.jpg')],
  'incline-dumbbell-press': [require('@/assets/demos/incline-dumbbell-press-0.jpg'), require('@/assets/demos/incline-dumbbell-press-1.jpg')],
  'knee-hip-raise-on-parallel-bars': [require('@/assets/demos/knee-hip-raise-on-parallel-bars-0.jpg'), require('@/assets/demos/knee-hip-raise-on-parallel-bars-1.jpg')],
  'leg-extensions': [require('@/assets/demos/leg-extensions-0.jpg'), require('@/assets/demos/leg-extensions-1.jpg')],
  'leg-press': [require('@/assets/demos/leg-press-0.jpg'), require('@/assets/demos/leg-press-1.jpg')],
  'leverage-iso-row': [require('@/assets/demos/leverage-iso-row-0.jpg'), require('@/assets/demos/leverage-iso-row-1.jpg')],
  'low-cable-crossover': [require('@/assets/demos/low-cable-crossover-0.jpg'), require('@/assets/demos/low-cable-crossover-1.jpg')],
  'lying-dumbbell-tricep-extension': [require('@/assets/demos/lying-dumbbell-tricep-extension-0.jpg'), require('@/assets/demos/lying-dumbbell-tricep-extension-1.jpg')],
  'lying-leg-curls': [require('@/assets/demos/lying-leg-curls-0.jpg'), require('@/assets/demos/lying-leg-curls-1.jpg')],
  'machine-bench-press': [require('@/assets/demos/machine-bench-press-0.jpg'), require('@/assets/demos/machine-bench-press-1.jpg')],
  'machine-bicep-curl': [require('@/assets/demos/machine-bicep-curl-0.jpg'), require('@/assets/demos/machine-bicep-curl-1.jpg')],
  'machine-preacher-curls': [require('@/assets/demos/machine-preacher-curls-0.jpg'), require('@/assets/demos/machine-preacher-curls-1.jpg')],
  'machine-shoulder-military-press': [require('@/assets/demos/machine-shoulder-military-press-0.jpg'), require('@/assets/demos/machine-shoulder-military-press-1.jpg')],
  'one-arm-dumbbell-row': [require('@/assets/demos/one-arm-dumbbell-row-0.jpg'), require('@/assets/demos/one-arm-dumbbell-row-1.jpg')],
  'one-arm-lat-pulldown': [require('@/assets/demos/one-arm-lat-pulldown-0.jpg'), require('@/assets/demos/one-arm-lat-pulldown-1.jpg')],
  'overhead-cable-curl': [require('@/assets/demos/overhead-cable-curl-0.jpg'), require('@/assets/demos/overhead-cable-curl-1.jpg')],
  'plank': [require('@/assets/demos/plank-0.jpg'), require('@/assets/demos/plank-1.jpg')],
  'pullups': [require('@/assets/demos/pullups-0.jpg'), require('@/assets/demos/pullups-1.jpg')],
  'push-ups-close-triceps-position': [require('@/assets/demos/push-ups-close-triceps-position-0.jpg'), require('@/assets/demos/push-ups-close-triceps-position-1.jpg')],
  'pushups': [require('@/assets/demos/pushups-0.jpg'), require('@/assets/demos/pushups-1.jpg')],
  'reverse-machine-flyes': [require('@/assets/demos/reverse-machine-flyes-0.jpg'), require('@/assets/demos/reverse-machine-flyes-1.jpg')],
  'romanian-deadlift': [require('@/assets/demos/romanian-deadlift-0.jpg'), require('@/assets/demos/romanian-deadlift-1.jpg')],
  'seated-cable-rows': [require('@/assets/demos/seated-cable-rows-0.jpg'), require('@/assets/demos/seated-cable-rows-1.jpg')],
  'seated-calf-raise': [require('@/assets/demos/seated-calf-raise-0.jpg'), require('@/assets/demos/seated-calf-raise-1.jpg')],
  'seated-leg-curl': [require('@/assets/demos/seated-leg-curl-0.jpg'), require('@/assets/demos/seated-leg-curl-1.jpg')],
  'side-lateral-raise': [require('@/assets/demos/side-lateral-raise-0.jpg'), require('@/assets/demos/side-lateral-raise-1.jpg')],
  'single-arm-cable-crossover': [require('@/assets/demos/single-arm-cable-crossover-0.jpg'), require('@/assets/demos/single-arm-cable-crossover-1.jpg')],
  'smith-machine-bench-press': [require('@/assets/demos/smith-machine-bench-press-0.jpg'), require('@/assets/demos/smith-machine-bench-press-1.jpg')],
  'smith-machine-incline-bench-press': [require('@/assets/demos/smith-machine-incline-bench-press-0.jpg'), require('@/assets/demos/smith-machine-incline-bench-press-1.jpg')],
  'smith-machine-squat': [require('@/assets/demos/smith-machine-squat-0.jpg'), require('@/assets/demos/smith-machine-squat-1.jpg')],
  'smith-machine-stiff-legged-deadlift': [require('@/assets/demos/smith-machine-stiff-legged-deadlift-0.jpg'), require('@/assets/demos/smith-machine-stiff-legged-deadlift-1.jpg')],
  'standing-biceps-cable-curl': [require('@/assets/demos/standing-biceps-cable-curl-0.jpg'), require('@/assets/demos/standing-biceps-cable-curl-1.jpg')],
  'standing-calf-raises': [require('@/assets/demos/standing-calf-raises-0.jpg'), require('@/assets/demos/standing-calf-raises-1.jpg')],
  'standing-low-pulley-deltoid-raise': [require('@/assets/demos/standing-low-pulley-deltoid-raise-0.jpg'), require('@/assets/demos/standing-low-pulley-deltoid-raise-1.jpg')],
  'standing-military-press': [require('@/assets/demos/standing-military-press-0.jpg'), require('@/assets/demos/standing-military-press-1.jpg')],
  'stiff-legged-dumbbell-deadlift': [require('@/assets/demos/stiff-legged-dumbbell-deadlift-0.jpg'), require('@/assets/demos/stiff-legged-dumbbell-deadlift-1.jpg')],
  'straight-arm-dumbbell-pullover': [require('@/assets/demos/straight-arm-dumbbell-pullover-0.jpg'), require('@/assets/demos/straight-arm-dumbbell-pullover-1.jpg')],
  'triceps-pushdown': [require('@/assets/demos/triceps-pushdown-0.jpg'), require('@/assets/demos/triceps-pushdown-1.jpg')],
  'upright-cable-row': [require('@/assets/demos/upright-cable-row-0.jpg'), require('@/assets/demos/upright-cable-row-1.jpg')],
  'wide-grip-lat-pulldown': [require('@/assets/demos/wide-grip-lat-pulldown-0.jpg'), require('@/assets/demos/wide-grip-lat-pulldown-1.jpg')],
} satisfies Record<string, Frames>;

const BY_NAME: Record<string, keyof typeof FRAMES> = {
  'smith machine bench press': 'smith-machine-bench-press',
  'smith machine larsen press': 'smith-machine-bench-press',
  'standing arnold press': 'arnold-dumbbell-press',
  'cable press-around': 'single-arm-cable-crossover',
  'cross-body cable y-raise': 'standing-low-pulley-deltoid-raise',
  'squeeze-only triceps pressdown': 'triceps-pushdown',
  'stretch-only overhead triceps extension': 'cable-rope-overhead-triceps-extension',
  'lat pulldown': 'wide-grip-lat-pulldown',
  'chest-supported row': 'leverage-iso-row',
  'dumbbell pullover': 'straight-arm-dumbbell-pullover',
  'rope face pull': 'face-pull',
  'dumbbell curl': 'dumbbell-bicep-curl',
  'machine preacher curl': 'machine-preacher-curls',
  'smith machine squat': 'smith-machine-squat',
  'smith machine paused squat': 'smith-machine-squat',
  'smith machine romanian deadlift': 'smith-machine-stiff-legged-deadlift',
  'dumbbell walking lunge': 'dumbbell-lunges',
  'seated leg curl': 'seated-leg-curl',
  'leg press calf raise': 'calf-press-on-the-leg-press-machine',
  'cable crunch': 'cable-crunch',
  'smith machine incline press': 'smith-machine-incline-bench-press',
  'machine shoulder press': 'machine-shoulder-military-press',
  'dumbbell skull crusher': 'lying-dumbbell-tricep-extension',
  'bent-over cable fly': 'cable-crossover',
  'dumbbell lateral raise': 'side-lateral-raise',
  'plate front raise': 'front-plate-raise',
  'diamond push-up': 'push-ups-close-triceps-position',
  'unilateral lat pulldown': 'one-arm-lat-pulldown',
  'pull-up': 'pullups',
  'kroc row': 'one-arm-dumbbell-row',
  'cable shrug': 'cable-shrugs',
  'reverse pec deck': 'reverse-machine-flyes',
  'overhead cable curl': 'overhead-cable-curl',
  'smith machine hip thrust': 'barbell-hip-thrust',
  'dumbbell stiff-leg deadlift': 'stiff-legged-dumbbell-deadlift',
  'leg press': 'leg-press',
  'lying leg curl': 'lying-leg-curls',
  'leg extension': 'leg-extensions',
  'seated calf raise': 'seated-calf-raise',
  "captain's chair leg raise": 'knee-hip-raise-on-parallel-bars',
  'squat': 'barbell-squat',
  'incline dumbbell press': 'incline-dumbbell-press',
  'ez-bar biceps curl': 'ez-bar-curl',
  'hanging leg raise': 'hanging-leg-raise',
  'bench press': 'barbell-bench-press-medium-grip',
  'low-to-high cable flye': 'low-cable-crossover',
  'romanian deadlift': 'romanian-deadlift',
  'triceps pressdown': 'triceps-pushdown',
  'smith machine shrug': 'barbell-shrug',
  'weighted pull-up': 'pullups',
  'cable row': 'seated-cable-rows',
  'standing calf raise': 'standing-calf-raises',
  'cable upright row': 'upright-cable-row',
  'hammer curl': 'hammer-curls',
  'reset deadlift': 'barbell-deadlift',
  'weighted dip': 'dips-chest-version',
  'cable overhead triceps extension': 'cable-rope-overhead-triceps-extension',
  'machine lateral raise': 'side-lateral-raise',
  'barbell overhead press': 'standing-military-press',
  'seated cable row': 'seated-cable-rows',
  'dumbbell concentration curl': 'concentration-curls',
  'push-ups': 'pushups',
  'incline bench press': 'barbell-incline-bench-press-medium-grip',
  'dumbbell fly': 'dumbbell-flyes',
  'cable fly': 'cable-crossover',
  'push-up': 'pushups',
  'machine chest press': 'machine-bench-press',
  'deadlift': 'barbell-deadlift',
  'barbell row': 'bent-over-barbell-row',
  'dumbbell row': 'one-arm-dumbbell-row',
  'overhead press': 'standing-military-press',
  'lateral raise': 'side-lateral-raise',
  'face pull': 'face-pull',
  'db shoulder press': 'dumbbell-shoulder-press',
  'cable lateral raise': 'standing-low-pulley-deltoid-raise',
  'barbell curl': 'barbell-curl',
  'cable curl': 'standing-biceps-cable-curl',
  'incline dumbbell curl': 'incline-dumbbell-curl',
  'machine biceps curl': 'machine-bicep-curl',
  'tricep pushdown': 'triceps-pushdown',
  'skull crusher': 'ez-bar-skullcrusher',
  'dip': 'dips-triceps-version',
  'back squat': 'barbell-squat',
  'front squat': 'front-barbell-squat',
  'leg curl': 'lying-leg-curls',
  'hip thrust': 'barbell-hip-thrust',
  'glute bridge': 'butt-lift-bridge',
  'calf raise': 'standing-calf-raises',
  'plank': 'plank',
  'crunch': 'crunches',
  'ab rollout': 'ab-roller',
  'abdominal machine': 'ab-crunch-machine',
};

export function normalizeExerciseName(name: string): string {
  return name
    .replace(/^(super ?set|giant set) \w+:\s*/i, '')
    .replace(/\s*\(.*?\)\s*/g, ' ')
    .replace(/[’‘]/g, "'")
    .replace(/\s+/g, ' ')
    .trim()
    .toLowerCase();
}

export function demoFor(name: string): Frames | undefined {
  const key = BY_NAME[normalizeExerciseName(name)];
  return key ? FRAMES[key] : undefined;
}
